# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
early_access: false
reviews:
  # enable automatic review and approval workflow
  request_changes_workflow: true
  # related_prs sometimes displays PRs that have a low-related PR
  related_prs: false
