[workspace]
members = [
    "templatia",
    "templatia-derive",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
authors = ["SHIMA0111<shima@little-tabby.com>"]
license = "MIT or Apache-2.0"
readme = "README.md"